# "$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]
search = "fd"
prepend_keymap = [
  { on = [
    "<S-Up>",
  ], run = "seek -5", desc = "Seek up 5 units in the preview" },
  { on = [
    "<S-Down>",
  ], run = "seek 5", desc = "Seek down 5 units in the preview" },
]
