# "$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

# Default keymaps
# https://github.com/sxyazi/yazi/blob/latest/yazi-config/preset/keymap.toml

[manager]
search = "fd"
prepend_keymap = [
  { on = [
    "<S-Up>",
  ], run = "seek -5", desc = "Seek up 5 units in the preview" },
  { on = [
    "<S-Down>",
  ], run = "seek 5", desc = "Seek down 5 units in the preview" },
  { on = [
    "<C-/>",
  ], run = "help", desc = "Show help" },
  { on = [
    "<F12>",
  ], run = "tasks_show", desc = "Show task manager" },
  { on = [
    "<CR>",
  ], run = "open --interactive --hover", desc = "Show context menu for hovered file" },
  { on = [
    "<C-t>",
  ], run = "tab_create", desc = "New tab" },
  { on = [
    "<C-j>",
  ], run = "tab_switch -1 --relative", desc = "Prev tab" },
  { on = [
    "<C-l>",
  ], run = "tab_switch +1 --relative", desc = "Next tab" },
  { on = [
    "t",
  ], run = "plugin --sync hide-preview", desc = "Show/hide preview" },
  { on = [
    "T",
  ], run = "plugin --sync max-preview", desc = "Maximize or restore preview" },
  { on = [
    "c",
    "m",
  ], run = "plugin chmod", desc = "Chmod on selected files" },
  { on = [
    "F",
  ], run = "plugin smart-filter", desc = "Smart filter" },
]

[tasks]
prepend_keymap = [{ on = ["<F1>"], run = "close", desc = "Close task manager" }]

[input]
prepend_keymap = [
  { on = [
    "<Esc>",
  ], run = "close", desc = "Abort input" },
  { on = [
    "<C-Backspace>",
  ], run = "kill backward", desc = "Backspace word" },
]

[help]
prepend_keymap = [
  { on = [
    "<PageUp>",
  ], run = "arrow -20", desc = "Move up n lines" },
  { on = [
    "<PageDown>",
  ], run = "arrow 20", desc = "Move down n lines" },
  { on = [
    "<Home>",
  ], run = "arrow -10000", desc = "Move to the beginning" },
  { on = [
    "<End>",
  ], run = "arrow 10000", desc = "Move to the end" },
  { on = [
    "<C-/>",
  ], run = "close", desc = "Close help" },
]
