# "$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

# https://yazi-rs.github.io/docs/configuration/yazi

[manager]
show_hidden = true
show_symlink = true
scrolloff = 3

[plugin]
prepend_preloaders = [{ mime = "image/heic", run = "heic" }]
