[aws]
disabled = true

[azure]
disabled = true

[dotnet]
disabled = true

[ruby]
disabled = true

[cmake]
disabled = true

[c]
disabled = true

[package]
disabled = true

[cmd_duration]
disabled = true

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = 'bold yellow'
ahead = '⇡'
behind = '⇣'
stashed = ''
up_to_date = ''
diverged = 'ʏ'
conflicted = 'C'
deleted = 'D'
renamed = 'R'
modified = '!'
staged = '+'
untracked = '?'
ignore_submodules = true
disabled = false

[git_state]
rebase = 'REBASING'
merge = 'MERGING'
revert = 'REVERTING'
cherry_pick = 'CHERRY-PICKING'
bisect = 'BISECTING'
style = 'bold yellow'
format = '([$state( $progress_current/$progress_total)]($style) )'
disabled = false

[git_branch]
format = '⋅ [$symbol$branch(:$remote_branch)]($style) '
symbol = ' '
style = 'bold blue'
disabled = false

[battery]
disabled = true

[python]
pyenv_version_name = true
pyenv_prefix = ''
format = '⋅ [${symbol}${pyenv_prefix}(${version} )]($style)[($virtualenv )](bold yellow)'
version_format = 'v${raw}'
style = 'blue bold'
symbol = 'Python '
disabled = false

[rust]
format = '⋅ [$symbol($version )]($style)'
version_format = 'v${raw}'
symbol = 'Rust '
style = 'bold blue'
detect_extensions = ['rs']
detect_files = ['Cargo.toml']
detect_folders = []
disabled = false

[nodejs]
format = '⋅ [$symbol($version )]($style)'
version_format = 'v${raw}'
symbol = 'Node '
style = 'bold blue'
detect_extensions = [
    'js',
    'mjs',
    'cjs',
    'ts',
    'mts',
    'cts',
]
detect_files = [
    'package.json',
    '.node-version',
    '.nvmrc',
]
detect_folders = ['node_modules']
disabled = false

[directory]
style = 'yellow bold'
disabled = false

[custom.arch]
# https://starship.rs/config/#custom-commands
# https://github.com/starship/starship/discussions/1252
command = 'echo $(arch)'
symbol = ' '
format = '⋅ [$symbol($output )]($style)'
style = 'bold yellow'
when = false